StravaWebsite-master/StravaMap/urls.py
from django import views
from django.urls import path, include

from StravaMap.models import Segment
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.shortcuts import render
from django.http import HttpResponse


urlpatterns = [
    path('', base_map, name='Base Map View'),    
    path('oauth/', include('social_django.urls', namespace='social')),     
    path('connected/', connected_map, name='Connect Map View'),                                       
    path('index/',base_map,name='index'),
    path('col_map/<str:col_id>', col_map, name = 'Col Map View'),
    path('act_map/<int:act_id>', act_map, name = 'Activity Map View'),          
    ###    
    path('activity/', ActivityListView.as_view(), name='activity'),        
    path('activity/<pk>', ActivityDetailView.as_view()),            
    path('activity/<int:act_id>/<int:col_id>/', col_map_by_act,name = "act-col"),            
    ###             
    path('cols_list/<str:pk>/', fColsListView,name='cols_list'),
    path('cols_list/<int:col_id>/', ColsDetailView.as_view(),name = "col-detail"),           
    path('cols/', ColsListView.as_view(), name='cols'),    
    path('cols/<pk>/', ColsDetailView.as_view(), name = "col-detail"),                           
    path('cols/<int:col_id>/<int:act_id>/', act_map_by_col, name = "col-act"),                           
    ###        
    path('colsok/', ColsOkListView.as_view(), name='colsok'),                           
    path('colsok/<pk>/', ColsDetailView.as_view(),name = "col-detail"),           
    path('colsok/<int:col_id>/<int:act_id>/', act_map_by_col, name = "col-act"),                                  
    ###
    path('cols06ko/', Cols06koListView.as_view(), name='cols06ko'),                    
    path('cols06ko/<pk>/', ColsDetailView.as_view(),name = "col-detail"),                           
    path('cols06ok/<int:col_id>/<int:act_id>/', act_map_by_col, name = "col-act"),    
    ### SEGMENTS
    path('dashboard/', User_dashboardView.as_view(), name='userdashboard'),            
    path('segment/',SegmentListView.as_view(), name='segment'),
    path('perform/',PerformListView.as_view(), name = 'perform'),         
    ### 
    path('calendar/',MonthStatListView.as_view(), name = 'calendar'),     
    ### FORM
    path('new_col/', new_col_form, name='new_col'),   
                    
]

urlpatterns += staticfiles_urlpatterns()

StravaWebsite-master/StravaWebsite/StravaWebsite/StravaWebsite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),    
]

StravaWebsite-master/StravaWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('StravaMap.urls')),             
]

StravaWebsite-master/StravaMap/models.py
from django.db import models
from StravaMap.vars import display_year_month

# Create your models here.

class Country(models.Model):			
	country_code = models.CharField(max_length=3, primary_key=True)
	country_name = models.CharField(max_length=50)
	country_lat = models.FloatField(null=True)
	country_lon = models.FloatField(null=True)
	code_100cols = models.CharField(max_length=3, null = True)
		
class Region(models.Model):			
	region_id = models.IntegerField(auto_created=True,  primary_key=True)
	region_name = models.CharField(max_length=50)
	region_code = models.CharField(max_length=50,null=True, default="")
	country_code = models.CharField(max_length=3, null=False, default="")	
	region_lat = models.FloatField(null=True)
	region_lon = models.FloatField(null=True)	
	
class Col(models.Model):		
	col_id = models.IntegerField(auto_created=True,  primary_key=True)
	col_name = models.CharField(max_length=200)
	col_code = models.CharField(max_length=20, null=True, unique=True)
	col_alt = models.IntegerField(null=True)	
	col_lat = models.FloatField(null=True)
	col_lon = models.FloatField(null=True)
	col_type = models.CharField(max_length=10, null= True)	

	def get_activities_passed(self):
		sc = self.col_code		
		q1 = Col_perform.objects.filter(col_code=sc)		
		return q1
	
class Activity(models.Model):
	act_id = models.IntegerField(null=False, primary_key=True)	
	strava_id = models.IntegerField(null=False, default=0)	
	strava_user_id	= models.IntegerField(null=False)	
	act_name = models.CharField(max_length=200, null=True, default="")
	act_start_date = models.DateTimeField(null=False)
	act_dist = models.FloatField(null=True)
	act_den =  models.IntegerField(null=True)
	act_type = models.CharField(max_length=10, null= True)
	act_time = models.IntegerField(null=True)	
	act_power = models.IntegerField(null=True)
	act_status = models.IntegerField(null=True)

	def get_act_dist_km(self):
		return self.act_dist/1000
	
	def get_col_passed(self):
		sc = self.strava_id		
		q1 = Col_perform.objects.filter(strava_id=sc)
		return q1
						
class 	Col_perform(models.Model):
	col_perf_id = models.IntegerField(auto_created=True,  primary_key=True)
	col_code = models.CharField(max_length=20, null=False, default="-" )
	strava_id = models.IntegerField(null=False)	### id activity

	class Meta:
		ordering = ['-strava_id']

	def get_col_name(self):		
		sc = self.col_code
		q1 = Col.objects.filter(col_code=sc)		
		return q1[0].col_name
	
	def get_col_id(self):		
		sc = self.col_code
		q1 = Col.objects.filter(col_code=sc)		
		return q1[0].col_id
			
class Col_counter(models.Model):
	col_count_id = models.IntegerField(auto_created=True,  primary_key=True)
	col_code = models.CharField(max_length=20, default="-")
	strava_user_id	= models.IntegerField(null=False)
	col_count = models.IntegerField(null=False)	
	year_col_count = models.IntegerField(null=False, default=0)	
	last_passage_date = models.DateTimeField(null=True)
	last_act_id = models.IntegerField(null=True)

	def get_col_name(self):		
		sc = self.col_code
		q1 = Col.objects.filter(col_code=sc)		
		return q1[0].col_name
	
	def get_col_id(self):		
		sc = self.col_code
		q1 = Col.objects.filter(col_code=sc)				
		return q1[0].col_id
	
	def get_col_alt(self):		
		sc = self.col_code
		q1 = Col.objects.filter(col_code=sc)		
		return q1[0].col_alt
		
	def get_country_name(self):		
		sc = self.col_code[0:2]			
		q1 = Country.objects.filter(code_100cols=sc)		
		return q1[0].country_name
	
	def get_region_name(self):		
		sc = self.col_code[0:2]				
		q1 = Country.objects.filter(code_100cols=sc)				
		country_code = q1[0].country_code		
		rc = self.col_code[3:5]
		#TODO
		if country_code == "ARG":
			rc = self.col_code[3:4]
		q2 = Region.objects.filter(country_code=country_code).filter(region_code=rc)
		region_name = "Not Found"
		for one in q2:
			region_name = one.region_name
		return region_name
	
	def get_country_region_code(self):		
		sc = self.col_code[0:5]						
		return sc
								
class Strava_user(models.Model):	
	id = models.IntegerField(auto_created=True,  primary_key=True)
	strava_user_id = models.IntegerField(null=True)
	strava_user = models.CharField(max_length=100, default="-") 
	first_name = models.CharField(max_length=100, default="-")
	last_name = models.CharField(max_length=100, default="-")
	token_type = models.CharField(max_length=100, default="-")
	access_token = models.CharField(max_length=100, default="-")
	refresh_token = models.CharField(max_length=100, default="-")
	expire_at = models.IntegerField(null=True)
	city = models.CharField(max_length=50, null=True)
	country = models.CharField(max_length=50, null=True)
	sex = models.CharField(max_length=100, null=True)

class Segment(models.Model):	
	segment_id = models.IntegerField(auto_created=True,  primary_key=True)
	strava_segment_id= models.IntegerField(null=True)
	activity_type = models.CharField(max_length=20, default="-")
	segment_name = models.CharField(max_length=100, default="-")
	slope =  models.FloatField(null=True)
	lenght = models.FloatField(null=True)
	ascent = models.FloatField(null=True)

class Perform(models.Model):
	perform_id = models.IntegerField(auto_created=True,  primary_key=True)
	strava_perf_id = models.IntegerField(null=True)
	segment_id = models.IntegerField(null=False)		
	strava_user_id = models.IntegerField(null=True)
	perf_date = models.DateTimeField(null=False)
	perf_chrono = models.IntegerField(null=False)
	perf_vam = models.IntegerField(null=False)
	perf_fc = models.IntegerField(null=False)
	perf_fcmax = models.IntegerField(null=False)

	def get_segment_name(self):		
		sid = self.segment_id
		q1 = Segment.objects.filter(segment_id=sid)		
		return q1[0].segment_name
	
	def get_segment_length(self):		
		sid = self.segment_id
		q1 = Segment.objects.filter(segment_id=sid)		
		return q1[0].lenght
	
	def get_segment_slope(self):		
		sid = self.segment_id
		q1 = Segment.objects.filter(segment_id=sid)		
		return q1[0].slope	
		
	def get_chrono_str(self):		
		secondes = self.perf_chrono
		sHeure = "0"
		sMinutes  = "00"
		sSecondes = "00"		
		heures = int(secondes/3600)
		if heures>0:
			sHeure = str(heures)
			secondes = secondes - heures*3600
		minutes = int(secondes/60)		
		if minutes>0:			
			sMinutes = "{:02d}".format(minutes)	 		
			secondes = secondes - minutes*60
		sSecondes = "{:02d}".format(secondes)	 		
		hms = sHeure+":"+sMinutes+":"+sSecondes
		return hms		

class User_var(models.Model):				
	id = models.IntegerField(auto_created=True,  primary_key=True)			
	strava_user_id = models.IntegerField(null=True)
	view_country_code = models.CharField(max_length=20, default="FRA")
	view_region_code = models.CharField(max_length=20, default="06")
	last_update = models.IntegerField(null=True)

class User_dashboard(models.Model):			
	id = models.IntegerField(auto_created=True,  primary_key=True)		
	strava_user_id = models.IntegerField(null=True)
	col_count = models.IntegerField(null=True)
	col2000_count = models.IntegerField(null=True)
	bike_year_km  = models.IntegerField(null=True)
	run_year_km  = models.IntegerField(null=True)

	def set_col_count(self):	
		nbCols = Col_counter.objects.filter(strava_user_id=self.strava_user_id).count()				
		# DB save		
		self.col_count = nbCols
		self.save()
		return nbCols
	
	def set_col2000_count(self):	
		## All Col Counter 		
		lcc = Col_counter.objects.filter(strava_user_id=self.strava_user_id)
		listeCC = []
		for one_cc in lcc:
			listeCC.append(one_cc.col_code)

		## All 2000  Cols
		q2000 = Col.objects.filter(col_alt__gt=1999)			
		liste2000 = []
		for one2000 in q2000:
			liste2000.append(one2000.col_code)

		### Intersection:
		passed2000 = [value for value in liste2000 if value in listeCC]    	
		nbCols2000 = len(passed2000)
		
		# DB save
		self.col2000_count = nbCols2000
		self.save()
		return nbCols2000
	
	def set_bike_year_km(self):	
		## All Activities 		
		
		lActivity = Activity.objects.filter(strava_user_id=self.strava_user_id).filter(act_start_date__gt="2023-01-01").filter(act_type="Ride")		
		distance_BY = 0		
		for one_act in lActivity:			
			distance_BY = distance_BY + one_act.act_dist/1000			
		
		self.bike_year_km = int(distance_BY)
		self.save()
				
		return self.bike_year_km
	
	def set_run_year_km(self):	
		## All Activities 		
		
		lActivity = Activity.objects.filter(strava_user_id=self.strava_user_id).filter(act_start_date__gt="2023-01-01").filter(act_type="Run")				
		distance_RY = 0
		for one_act in lActivity:
			distance_RY = distance_RY + one_act.act_dist/1000
					
		self.run_year_km = int(distance_RY)
		self.save()
				
		return self.run_year_km
	
class Month_stat(models.Model):					
	month_stat_id = models.IntegerField(auto_created=True,  primary_key=True)
	strava_user_id = models.IntegerField(null=True)
	yearmonth = models.CharField(max_length=6, default="190000")
	days_on = models.IntegerField(null=True)
	bike_km = models.IntegerField(null=True)
	bike_ascent = models.IntegerField(null=True)
	bike_time = models.IntegerField(null=True)
	col_count = models.IntegerField(null=True)
	col2000_count = models.IntegerField(null=True)
	top_alt_col = models.IntegerField(null=True)

	def yearmonth_html(self):
		annee = self.yearmonth[0:4]
		mois = int(self.yearmonth[4:])		
		mois_str = display_year_month(mois) 
		return  mois_str + " " + annee
	
	def get_chrono_str(self):		
		secondes = self.bike_time
		sHeure = "0"
		sMinutes  = "00"
		sSecondes = "00"		
		heures = int(secondes/3600)
		if heures>0:
			sHeure = str(heures)
			secondes = secondes - heures*3600
		minutes = int(secondes/60)		
		if minutes>0:			
			sMinutes = "{:02d}".format(minutes)	 		
			secondes = secondes - minutes*60
		sSecondes = "{:02d}".format(secondes)	 		
		hms = sHeure+"h"+sMinutes
		return hms		

	

StravaWebsite-master/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Des cols et 100 Cols</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  {% load static %}
  <script src="{% static 'menu.js' %}"></script>
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">     
  
</head>
<body>      
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
          {% block sidebar %}
          {% load static %} <center><a href="{% url 'index' %}"><img src="{% static '/image/124_club-des-cent-cols.png' %}"  /></a></center>
          <script src="{% static 'sortable.min.js' %}"></script>
          <link rel="stylesheet" href="{% static 'css/grid.css' %}">
                    
          <br>                              
          <ul class="sidebar-nav">                                                   
                        
            {% if countries %}  
            <li><b><a>Cols</a></b></li>              
              <br>
              <select id = "country" name="country" onChange="country(this.value)">                                
                <option value="">--- Pays ---</option>
                {% for p in countries %}                              
                  <option value={{p.country_code}}>{{p.country_name}}</option>                                    
                {% endfor %}  
              </select>   

              <br><br>         

              <select id = "region" name="region" onChange="region(this.value)">
                <option value="">--- Département ---</option>  
                {% for r in regions %}    
                  
                  <option value={{r.region_code}}>{{r.region_name}}</option>                     
                  
                  <script type="text/javascript">                                    

                  region_name = "{{r.region_name}}";      
                  region_code = "{{r.region_code}}";                                       
                  region_country = "{{r.country_code}}";                                           
                  region_id = "{{r.region_id}}";

                  region_name_list.push(region_name);                        
                  region_code_list.push(region_code);   
                  region_country_list.push(region_country);   
                  region_id_list.push(region_id);   
                  </script>

                {% endfor %}  
                
              </select>   

              <br><br>             
            {% endif %}  
            <li><a href="{% url 'cols' %}">Tous les Cols</a></li>                                    
            <li><a href="{% url 'colsok' %}">Cols franchis</a></li>            
            <li><a href="{% url 'cols06ko' %}">Col des Alpes-Maritimes Restants</a></li>                                                                                                                    
            <li><a href="{% url 'activity' %}">Flux des activités</a></li>                   
            <li><a href="{% url 'userdashboard' %}">Dashboard</a></li>            
            <li><a href="{% url 'calendar' %}">Statistiques Mensuelles</a></li>            
           </ul>
          {% endblock %}
      </div>
         <div class="col-sm-10 ">
             {% block content %}               
             {% endblock %}            
         </div>
    </div>
  </div>


  <script>
    var table = document.querySelector('.massive')
    var tbody = table.tBodies[0]
    var rows = [].slice.call(tbody.rows, 0)
    var fragment = document.createDocumentFragment()
  
    for (var k = 0; k < 50; k++) {
      for (var i = 0; i < rows.length; i++) {
        fragment.appendChild(rows[i].cloneNode(true))
      }
    }
    tbody.innerHTML = ''
    tbody.appendChild(fragment)
  </script>
  
  <script>
    function prepareAdvancedTable() {
      var size_table = document.querySelector('.advanced-table')
      var rows = size_table.tBodies[0].rows    
      for (let i = 0; i < rows.length; i++) {
        const date_element = rows[i].cells[2]
        const size_element = rows[i].cells[1]
        date_element.setAttribute('data-sort', date_element.innerText.replace(/(\d+)\/(\d+)\/(\d+)/, '$3$1$2'))
        size_element.setAttribute('data-sort', toBytes(size_element.innerText))
      }
    }
  
    function toBytes(size) {
      const units = [, 'k', 'm', 'g', 't']
      const match = size.match(/(\d+\.\d+|\d+)\s*([kmgt])b?/i)
      if (!match) return parseFloat(size)
      const [value, unit] = match.slice(1)
      const index = units.indexOf(unit.toLowerCase())
      return Math.round(parseFloat(value) * Math.pow(1024, index))
    }
    prepareAdvancedTable()
  </script>  

</body>
</html>

StravaWebsite-master/templates/base_map.html
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>StravaMap</title>
  
  </head>
      {% block content %}      
      <!--Begin Map Container-->
      {{ main_map|safe }}             
      <!--End Map Container-->
      {% endblock %}
     
   
</html>

StravaWebsite-master/templates/cols_list.html
{% extends "base_generic.html" %}

{% block content %}
  <br />
  <h3>[{{country}}] {{region}}</h3>  
  <h3>Liste des cols:</h3>  
  <br />
  {% load static %} <a href="{% url 'index' %}"><img src="{% static '/image/map.png' %}"  /> Voir sur la carte</a>   
  {% if col_list %}
  <br />
  <table class="sortable n-last">
    <thead>
    <tr>         
        <th class="indicator-left">Nom</th>
        <th class="indicator-left">Altitude</th>
        <th class="indicator-left">Code 100 cols</th>     
        <th class="indicator-left">Route/Piste/Sentier</th>     
    </tr>  
    </thead>    
    
    <tbody>
                  
    {% for col in col_list %}    
      <tr>
        <td>          
          <a href="/cols/{{ col.col_id }}">{{ col.col_name }}</a>                     
        </td>  
        <td data-sort={{col.col_alt}}>{{col.col_alt}} m  </td>
        <td>{{col.col_code}}</td>
        <td>{{col.col_type}}</td>
      </tr>  

    {% endfor %}
  </tbody>
  </table>  
  {% else %}
    <p>There are no Col in the Database.</p>
  {% endif %}
{% endblock %}

StravaWebsite-master/templates/index.html
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>StravaMap</title>
  
  </head>

<!--NavBar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <!--Begin Strava Connect Button-->
      <form class="form-inline my-2 my-lg-0">
              <a href="{% url 'social:begin' 'strava' %}" class="btn btn-primary" role="button"
            aria-disabled="true">Connect to Strava</a>
      </form>
      <!--End Strava Connect Button-->
  </div>
</nav>
<!--End NavBar-->

<div class="container-fluid">  
  <div class="row">
    <div class="col-sm-2">
        {% block sidebar %}                       
         <ul class="sidebar-nav">    
            {% load static %} <a href="{% url 'index' %}"><img src="{% static '/image/124_club-des-cent-cols.png' %}"  /></a>
                                 
            <li><a href="{% url 'cols' %}">Tous les Cols</a></li>                                    
            <li><a href="{% url 'colsok' %}">Cols franchis</a></li>            
            <li><a href="{% url 'cols06ko' %}">Col des Alpes-Maritimes Restants</a></li>                                    
            <li><a href="{% url 'activity' %}">Flux des activités</a></li>                   
            <li><a href="{% url 'userdashboard' %}">Dashboard</a></li>      
            <li><a href="{% url 'calendar' %}">Statistiques Mensuelles</a></li>                                
            <li><a href="{% url 'new_col' %}">Nouveau col</a></li>                                
    
         </ul>
        {% endblock %}

    </div>
    <div class="col-sm-10 ">
      {% block content %}      
      <!--Begin Map Container-->
        <div class="my_container">
          <div class="row mt-4">            
              <div class="col-md-10 offset-md-1">
                  {{ main_map|safe }}
              </div>              
          </div>
        </div>
      <!--End Map Container-->
      {% endblock %}
     
    </div>    
  </div>  
</div>

</html>

StravaWebsite-master/templates/new_col.html
{% extends "base_generic.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nouveau Col</title>
</head>
<body>  
<h2>Saisie d'un nouveau col</h2>    

<form method="POST" action="">
    {% csrf_token %} 

<table>
    <tr>
        <td>Nom du col</td>
        <td>{{form.col_name}} </td>    
    </tr>
    <tr>
        <td>Col Code</td>
        <td>{{form.col_code}} </td>        
    </tr>
    <tr>
        <td>Altitude</td>
        <td>{{form.col_alt}}</td>
        
    </tr>
    <tr>
        <td>Latitude</td>
        <td>{{form.col_lat}}</td>        
    </tr>
    <tr>
        <td>Longitude</td>
        <td>{{form.col_lon}}<td>        
    </tr>
    <tr>
        <td>Route/Piste/Sentier</td>
        <td>{{form.col_type}}</td>        
    </tr>
</table>
      
    <br>
    <input type="submit" value=Enregistrer> 
</form> 
 
</body>
</html>

{% endblock %}